spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dataminingexp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/peeka/mapper/xml/*.xml
server:
  port: 8181

